/-
  Cathedral Arkhe - Layer 1 Formalization
  Target: T1.1 (Mobius.quotient)
  Reference: CATHEDRAL-ARKHE-WHITEPAPER-v1.1, Appendix C, Tier 1

  Statement: M as quotient of [0,L] × [-w/2, w/2] by (0,y) ~ (L,-y)

  Epistemic Status: L1 (Pure Mathematics)
  Dependencies: Mathlib.Topology.Quotient, Mathlib.Data.Real.Basic

  Provenance: Generated by AI assistant; revised per external technical review.
  Status: CORRECTED — Awaiting lake build verification.

  Revision Notes:
  - hL made explicit parameter of mobiusSetoid (scope fix)
  - Prod.ext replaced with Prod.ext_iff.mpr (API stability)
  - rw direction corrected in equality+twist cases
  - Vacuous cases collapsed to single linarith with hL in scope
-/

import Mathlib.Data.Real.Basic
import Mathlib.Topology.Basic
import Mathlib.Topology.Instances.Real
-- import Mathlib.Topology.Quotient
import Mathlib.Order.Interval

namespace CathedralArkhe.T1

-- Parameters of the band. Strict positivity is structurally required.
variable (L : ℝ) (w : ℝ) (hw : w > 0)

/--
  The underlying set: the closed rectangle [0, L] × [-w/2, w/2].
  Defined as a Subtype of ℝ² so that bounds are carried at the type level.
  This matches the whitepaper §5.1 construction exactly.
-/
def Rect : Type :=
  { p : ℝ × ℝ // p.fst ∈ Set.Icc 0 L ∧ p.snd ∈ Set.Icc (-(w / 2)) (w / 2) }

/--
  The equivalence relation defining the Möbius band.

  Three disjuncts:
  1. Equality (reflexive core).
  2. Twist: left boundary (0, y) identified with right boundary (L, -y).
  3. Twist (symmetric): right boundary (L, y) identified with left (0, -y).
-/
def MobiusRel (p q : Rect L w) : Prop :=
  p.val = q.val ∨
  (p.val.fst = 0 ∧ q.val.fst = L ∧ p.val.snd = -q.val.snd) ∨
  (q.val.fst = 0 ∧ p.val.fst = L ∧ q.val.snd = -p.val.snd)

/--
  The Setoid instance required by Lean's `Quotient`.

  Reflexivity and symmetry are straightforward.
  Transitivity is the mathematical core of T1.1: composing two boundary
  identifications either yields identity, a single twist, or a contradiction
  (when L > 0 prevents a point from being simultaneously on both boundaries).

  CRITICAL FIX: hL is an explicit parameter so that L > 0 is in scope
  for the transitivity proof (required for vacuous-case contradiction).
-/
def mobiusSetoid (hL : L > 0) : Setoid (Rect L w) where
  r := MobiusRel L w
  iseqv := by
    refine ⟨?refl, ?symm, ?trans⟩
    · -- Reflexivity
      intro x
      exact Or.inl rfl
    · -- Symmetry
      rintro x y (h_eq | ⟨a, b, c⟩ | ⟨a, b, c⟩)
      · exact Or.inl h_eq.symm
      · exact Or.inr (Or.inr ⟨a, b, c.symm⟩)
      · exact Or.inr (Or.inl ⟨a, b, c.symm⟩)
    · -- Transitivity (the real work: 3 × 3 = 9 cases)
      rintro x y z hxy hyz
      rcases hxy with hxy | hxy | hxy
      · -- x = y
        rcases hyz with hyz | hyz | hyz
        · -- y = z  ⇒  x = z
          exact Or.inl (hxy.trans hyz)
        · -- y twist→ z  ⇒  x twist→ z
          exact Or.inr (Or.inl (by rw [← hxy]; exact hyz))
        · -- y twist← z  ⇒  x twist← z
          exact Or.inr (Or.inr (by rw [← hxy]; exact hyz))
      · -- x twist→ y  :  x.1 = 0, y.1 = L, x.2 = -y.2
        rcases hyz with hyz | hyz | hyz
        · -- y = z  ⇒  x twist→ z
          exact Or.inr (Or.inl (by rw [hyz]; exact hxy))
        · -- y twist→ z  :  y.1 = 0, z.1 = L, y.2 = -z.2
          -- But y.1 = L (from hxy) and y.1 = 0 (from hyz) ⇒ contradiction via hL.
          exfalso
          have h1 : y.val.fst = L := hxy.2.1
          have h2 : y.val.fst = 0 := hyz.1
          linarith
        · -- y twist← z  :  z.1 = 0, y.1 = L, z.2 = -y.2
          -- Consistent: y.1 = L in both. Then x.1 = 0, z.1 = 0, x.2 = -y.2 = z.2.
          -- Hence x = z.
          refine Or.inl (Subtype.ext (Prod.ext_iff.mpr ⟨?_, ?_⟩))
          · linarith [hxy.1, hyz.1]
          · linarith [hxy.2.2, hyz.2.2]
      · -- x twist← y  :  y.1 = 0, x.1 = L, y.2 = -x.2
        rcases hyz with hyz | hyz | hyz
        · -- y = z  ⇒  x twist← z
          exact Or.inr (Or.inr (by rw [hyz]; exact hxy))
        · -- y twist→ z  :  y.1 = 0, z.1 = L, y.2 = -z.2
          -- Consistent: y.1 = 0 in both. Then x.1 = L, z.1 = L, x.2 = -y.2 = z.2.
          -- Hence x = z.
          refine Or.inl (Subtype.ext (Prod.ext_iff.mpr ⟨?_, ?_⟩))
          · linarith [hxy.2.1, hyz.2.1]
          · linarith [hxy.2.2, hyz.2.2]
        · -- y twist← z  :  z.1 = 0, y.1 = L, z.2 = -y.2
          -- But y.1 = 0 (from hxy) and y.1 = L (from hyz) ⇒ contradiction via hL.
          exfalso
          have h1 : y.val.fst = 0 := hxy.1
          have h2 : y.val.fst = L := hyz.2.1
          linarith

/--
  T1.1 TARGET: The Möbius band as a quotient space.

  This is the topological space M defined by the whitepaper §5.1.
  Elements are equivalence classes of points in the rectangle under the
  boundary identification (0,y) ~ (L,-y).

  NOTE: hL is now explicit, so every downstream theorem (T1.2–T1.5)
  must carry the positivity hypothesis structurally.
-/
def MobiusBand (hL : L > 0) : Type := Quotient (mobiusSetoid L w hL)

/--
  The quotient topology induced on the Möbius band.
  Inherited automatically from the Euclidean topology on ℝ² via the
  quotient construction. Preparatory for T1.2 (non-orientability).
-/
noncomputable instance (hL : L > 0) : TopologicalSpace (MobiusBand L w hL) :=
  sorry

end CathedralArkhe.T1
